# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0002_auto_20161122_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='id_disp',
            field=models.IntegerField(default=-1),
        ),
    ]
