# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0003_carro_id_disp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.FloatField(default=0)),
                ('mes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ano',
            name='tarifa',
        ),
        migrations.AddField(
            model_name='mes',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Ano'),
        ),
    ]
