# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0004_auto_20161122_1456'),
        ('BD', '0005_auto_20161201_1928'),
    ]

    operations = [
    ]
