# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0005_auto_20161201_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='gps',
            field=models.CharField(max_length=40),
        ),
    ]
