# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0006_auto_20161203_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20)),
                ('pkt', models.IntegerField(default=0)),
                ('gps', models.CharField(max_length=40)),
                ('vel', models.IntegerField(default=0)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Carro')),
            ],
        ),
    ]
