# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0006_merge_20161203_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='id_disp',
        ),
        migrations.RemoveField(
            model_name='mes',
            name='tarifa',
        ),
        migrations.AlterField(
            model_name='msg',
            name='gps',
            field=models.CharField(max_length=40),
        ),
    ]
